// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo6y3zpBIcVmIjwbw0ulFFeZhbcqjVDJs',
    appId: '1:70340238090:web:3bc628e6238a289ef3f8f3',
    messagingSenderId: '70340238090',
    projectId: 'pushnotifications-9c4cf',
    authDomain: 'pushnotifications-9c4cf.firebaseapp.com',
    storageBucket: 'pushnotifications-9c4cf.appspot.com',
    measurementId: 'G-7QP7MDJ7FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-QxcRaDCjDkcEs8jjF-f4cmG-3jM1lis',
    appId: '1:70340238090:android:72ccad9fc229bf73f3f8f3',
    messagingSenderId: '70340238090',
    projectId: 'pushnotifications-9c4cf',
    storageBucket: 'pushnotifications-9c4cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcUFQrpa9Wi9xYM0s0Pl1K-iVn9VV7oCA',
    appId: '1:70340238090:ios:b700071b8a5ce103f3f8f3',
    messagingSenderId: '70340238090',
    projectId: 'pushnotifications-9c4cf',
    storageBucket: 'pushnotifications-9c4cf.appspot.com',
    iosBundleId: 'com.example.pushNotificationsFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcUFQrpa9Wi9xYM0s0Pl1K-iVn9VV7oCA',
    appId: '1:70340238090:ios:b700071b8a5ce103f3f8f3',
    messagingSenderId: '70340238090',
    projectId: 'pushnotifications-9c4cf',
    storageBucket: 'pushnotifications-9c4cf.appspot.com',
    iosBundleId: 'com.example.pushNotificationsFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo6y3zpBIcVmIjwbw0ulFFeZhbcqjVDJs',
    appId: '1:70340238090:web:151b59bd66617879f3f8f3',
    messagingSenderId: '70340238090',
    projectId: 'pushnotifications-9c4cf',
    authDomain: 'pushnotifications-9c4cf.firebaseapp.com',
    storageBucket: 'pushnotifications-9c4cf.appspot.com',
    measurementId: 'G-5J1Y1R3R0E',
  );
}
